#!/usr/bin/lua

-- FWWRT authentication portal helper methods
--
-- Daniel Podolsky, tpaba@cpan.org, 2009-08-04
-- Roman Belyakovsky, roman.belyakovsky@gmail.com
-- Licence is the same as OpenWRT

module("fwwrt.basicadmin", package.seeall)

--require "profiler"
--prof=0

require "luasql.sqlite"

require "fwwrt.authportal"
require "fwwrt.crypt"

local webDir     = fwwrt.util.uciGet('httpd.httpd.home',            'string')
local hostname   = fwwrt.util.uciGet('fwwrt.authportal.httpsName',  'string')
local ssid       = fwwrt.util.uciGet('wireless.wifi-iface.ssid',  'string')
local cardsTempl=fwwrt.util.fileToVariable(webDir.."/cards.template")
local tableTempl = fwwrt.util.fileToVariable(webDir.."/cardTable.template")
local rowsTempl = fwwrt.util.fileToVariable(webDir.."/cardRows.template")
local cardTempl = fwwrt.util.fileToVariable(webDir.."/card.template")
local cardGenTempl = fwwrt.util.fileToVariable(webDir.."/cardGen.template")
local dynamicUserTempl = fwwrt.util.fileToVariable(webDir.."/dynamicUser.template")

dbCon = fwwrt.dbBackend.connect()

function checkLoginPost(request)
	if request.method == 'POST' 
		and request.POST.oplogin 
		and request.POST.opname 
		and request.POST.oppass then
			return checkOpLogin(request.POST.opname, request.POST.oppass)
	end
	return nil
end

function checkOpLogin(user, pass)
	local cur = assert (dbCon:execute(string.format([[
         select * from operators where opname = '%s' and oppass = '%s']], user, pass))
	)
	-- row = cur:fetch ({}, "a")	-- the rows will be indexed by field names
	local result = cur:fetch({}, "a")
	cur:close()
	return result and result.opname or nil
end

function insertUser(user) --should sheck values and return errors correctly todo
	local cur = dbCon:prepare"INSERT INTO users(username, password, tarifid, autogenerated) VALUES(?,?,?,?)"
	cur:bind({"TEXT", user},{"TEXT", "nopass"},{"INTEGER",1}, {"BOOLEAN", true})
	return assert(cur:execute()) -- executes the prepared statement, accetr? todo
--	return true --do we need this? todo
end

function autoMakeUser() --passLength
	local abiturient
	local tries = 0
	local success, result
	repeat
		abiturient = fwwrt.crypt.randomString()
		success, result = pcall(insertUser,abiturient) -- ~= true and tries < 50 do
		tries = tries + 1
	until success or tries > 50
	if not success then
		error(string.format("user is not added in %d tries: %s", tries, tostring(result)))
	end
--	print("user added in "..tries.." tries ==================================================")
	return abiturient
end

function checkCookie(cookie, ip) --todo: improve me
	local encOperand = string.sub(cookie,string.len("operator=\"")+1, -2)
	local operand = fwwrt.crypt.decrypt(encOperand)
--	print("shecking cookie, encript: "..tostring(operand).."")
	if (not operand) then return nil end
	_,_,operator,cookieip,expire = string.find(operand,"^(%S+)%s+(%S+)%s+(%S+)$")
	if (operator and cookieip == ip and fwwrt.util.a2i(expire) > os.time()) then return operator end
	return nil
end

function makeCookieHeaders(wsapi_env, operator)
	local expire = os.time()+3600
	local expireString	= os.date ("!%a, %d-%b-%Y %H:%M:%S GMT",expire)
	local cookedHeaders = commonHeaders
	local operand = operator.." "..wsapi_env.REMOTE_ADDR.." "..expire
	local encOperand = fwwrt.crypt.encrypt(operand)
	cookedHeaders = {["Set-Cookie"] = "operator=\""..encOperand.."\"; expires="..expireString..";secure"}
	return cookedHeaders
end

function makeNoCookieHeaders()
	local expire = os.time()-3600
	local expireString	= os.date ("!%a, %d-%b-%Y %H:%M:%S GMT",expire)
	local cookedHeaders = commonHeaders
	cookedHeaders = {["Set-Cookie"] = "operator=nooperator; expires="..expireString..";secure"}
	return cookedHeaders
end

function doAdmin(wsapi_env, request) --generate cards, create users
	local time1=os.time()
	local width="40%"
	local height="85mm"
--	local pt=5 --cards per page
--	local row=pt*number
--	local col=2
--	local request = wsapi.request.new(wsapi_env)
--	coroutine.yield("<pre>"..printTable(request, "request", ".", 10).."</pre>")
	local countP = request.POST.count or math.floor((request.POST.cardsCount-1)/10)+1
--	print(math.floor(9/10)+1)
--	local note = request.POST.note
	local useIn = {}
	useIn.day = 24*60*60
	useIn.week, useIn.month, useIn.year =
	useIn.day*7,useIn.day*31-12*60*60,useIn.day*365
--	local useBy = os.time() + useIn[request.POST.useIn]
	
-- 	local expireIn = request.POST.eMinute*60 + 
-- 	request.POST.eHour*60*60 + request.POST.eDay*60*60*24 + 
-- 	request.POST.eMonth*60*60*24*30+60*60*12 + request.POST.eYear*60*60*24*365
	
	local passLength = 8
	local function multiplyStrings (text, count)
		local ntext = ""
		for i = 1, count do
		 	ntext = ntext..text
		end
		return ntext
	end
	local s = 234
	cards=("$do_cosm[["..cardsTempl.."]]")
	cardValues = {
		do_cosm = function()
			cosmo.yield{
				tables = multiplyStrings("$do_cosm[["..tableTempl.."]]", countP),
				rows = "$do_cosm[["..rowsTempl.."]]",
				card = "$do_cosm[["..cardTempl.."]]",
				dynamicUser = "$do_dynamic[["..dynamicUserTempl.."]]",
				ssid = ssid,
--				note = "i = '"..s.."'",
				height = height,
				width = width
--				expireIn = expireIn
			}
		end,
		do_dynamic = function()
			cosmo.yield{
				user = autoMakeUser() --user(s)
			}
		end
		}
	i = 0
--	profiler.start()
	while string.find(cards, "%$") ~= nill and i < 10 do
--		usertempl
		cards = cosmo.fill(cards,cardValues)
		print("filling template... Level "..i)
		i = i + 1
	end
--	profiler.stop()
	print("ok, page ready to show")
--	print(cards)
	coroutine.yield(cards)
--	test(wsapi_env)
	print("3003")
	local time2=os.time()
	print("generating users done in "..time2-time1.." seconds")
	print("flush")
end

function showAdminLogin(wsapi_env, headers)
	local reason = reason or ""
	local template  = fwwrt.util.fileToVariable(webDir.."/showAdminLogin.template")
	local values    = {actionUrl = "https://"..wsapi_env.SERVER_NAME.."/admin"
	                  ,reason    = reason}
	local process = function () coroutine.yield(cosmo.fill(template, values)) end
	return 200, headers, coroutine.wrap(process)
end

function showBasicAdminForm(wsapi_env, operator)
	local template  = cardGenTempl
	local values = {actionUrl = "https://"..wsapi_env.SERVER_NAME.."/admin"}
	local process = function () coroutine.yield(cosmo.fill(template, values)) end
	return 200, makeCookieHeaders(wsapi_env, operator), coroutine.wrap(process)
end

function processBasicAdminForm(wsapi_env) --main, 
	local request  = wsapi.request.new(wsapi_env)
	print("cookie = '"..tostring(wsapi_env.HTTP_COOKIE).."'")
	local operator = checkCookie(wsapi_env.HTTP_COOKIE, wsapi_env.REMOTE_ADDR)
	                 or checkLoginPost(request)
	print("operator = "..tostring(operator))
	if ( operator ) then
		if (request.method == 'POST' and request.POST.generate) then
			local callDoAdmin = function() return doAdmin(wsapi_env, request) end
			return 200, makeCookieHeaders(wsapi_env, operator), coroutine.wrap(callDoAdmin)
		elseif (request.method == 'POST' and request.POST.logout) then
			return showAdminLogin(wsapi_env, makeNoCookieHeaders())
		else
			return showBasicAdminForm(wsapi_env, operator)
		end
	else
		return showAdminLogin(wsapi_env, commonHeaders)
	end
end