DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tarifs;
DROP TABLE IF EXISTS userinfo;
DROP TABLE IF EXISTS tarifinfo;
-- CREATE TABLE users
--     (userid   BIGINT  PRIMARY KEY NOT NULL,
--     username CHAR(16) NOT NULL UNIQUE
--     );

create table users(
    userid integer primary key, 
    username char(16) not null unique,
    password char(16) not null, -- change to hash
    tarifid integer not null default 0,
    totalTrafUsed integer not null default 0, 
    sessionTrafUsed integer not null default 0,
    totalTimeUsed integer not null default 0,
    sessionTimeUsed integer not null default 0,
    sessionsUsed integer not null default 0,
    autogenerated boolean not null default false
    );

create table activeusers(
    ipaddr char unique,
    userid integer,
    logintime integer,
    macaddr char(17)
    );

-- create unique index on activeusers (ipaddr);
    
create table tarifs(
    tarifid integer primary key, 
    multisession boolean,
    totalTrafLim integer,
    sessTrafLim integer,
    totalTimeLim integer, 
    sessTimeLim integer,
    sessInterval integer,
    hiSpeedTrafLim integer,
    hiSpeedLim integer,
    expireDate integer, --date longint?
    sessPerPeriod integer,
    sessCountPeriod char(8)
    );
create table userinfo(
    userid integer
    );
create table tarifinfo(
    tarifid integer,
    tarifdesription varchar
    );
-- CONSTRAINT fk_foo_id REFERENCES a(id) ON DELETE CASCADE http://justatheory.com/computers/databases/sqlite/foreign_key_triggers.html

    
create table operators(
    opid integer primary key,
    opname char(16) not null unique,
    oppass char(16) not null -- change to hash
    );

    insert into operators(opname, oppass) values ("root", "toor");
    insert into tarifs(multisession, totalTimeLim) values ("false", 24*60*60); -- users expire based on timelim 
    insert into users(username, password, tarifid, autogenerated) values ("test", "nopass", 1, "true");